- hosts: jabberserver 
  tasks:
  - name: set hostname on boot to short name from inventory list
    action: template src=/Users/nhagge/Dropbox/ansible_playbooks/templates/etc_hostname.j2
            dest=/etc/hostname
            owner=root group=root mode=0644
            backup=yes
    register: hostname_file

  - name: change hostname on running system
    action: command hostname -F /etc/hostname
##    only_if: '${hostname_file.changed}'
