- hosts: vm
  tasks:
   - name: Install Apache2
     apt: pkg=apache2 update_cache=yes state=latest
   - name: Copy config-file ...
     copy: src=/Users/nhagge/Dropbox/ansible_playbooks/templates/cnf.cnf dest=/etc/apache2/foo.conf owner=root group=root mode=0644 backup=yes
   - name: Set sym links ...
     file: src=/etc/apache2/mods-available/vhost_alias.load dest=/etc/apache2/mods-enabled/vhost_alias.load state=link 
   - name: enabled mod_rewrite
     apache2_module: name=rewrite state=present
     #notify:
     #- restart apache2
   - name : restart apache2
     # service: name=apache2 state=restarted
     service: name=apache2 state=restarted

