- hosts: vm 
  tasks:
   - name: Install aptitude
     apt: pkg=aptitude state=installed
   - name: Update repository
     apt: update_cache=yes # upgrade=yes
   - name: Upgrade repository
     apt: upgrade=yes
   - name: Install htop
     apt: pkg=htop state=installed
   - name: Install dstat
     apt: pkg=dstat state=installed
   - name: Install atop
     apt: pkg=atop state=installed 
   - name: Install vim
     apt: pkg=vim state=installed
   - name: Install lynx
     apt: pkg=lynx state=installed
   - name: Install netcat 6
     apt: pkg=netcat6 state=installed
   - name: Install nmap
     apt: pkg=nmap state=installed
   - name: Install git
     apt: pkg=git state=installed force=yes
   - name: Install tmux
     apt: pkg=tmux state=present
